//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace ConsultaCotacaoClient.br.com.riscozeroprojetos.consultacotacao {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CotacaoServiceSoap", Namespace="http://cotacao.sjdr.com.br/")]
    public partial class CotacaoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObterCotacoesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterCotacaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CotacaoService() {
            this.Url = global::ConsultaCotacaoClient.Properties.Settings.Default.ConsultaCotacaoClient1_br_com_riscozeroprojetos_consultacotacao_CotacaoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObterCotacoesCompletedEventHandler ObterCotacoesCompleted;
        
        /// <remarks/>
        public event ObterCotacaoCompletedEventHandler ObterCotacaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cotacao.sjdr.com.br/ObterCotacoes", RequestNamespace="http://cotacao.sjdr.com.br/", ResponseNamespace="http://cotacao.sjdr.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DadosCotacao[] ObterCotacoes(string[] codPapel) {
            object[] results = this.Invoke("ObterCotacoes", new object[] {
                        codPapel});
            return ((DadosCotacao[])(results[0]));
        }
        
        /// <remarks/>
        public void ObterCotacoesAsync(string[] codPapel) {
            this.ObterCotacoesAsync(codPapel, null);
        }
        
        /// <remarks/>
        public void ObterCotacoesAsync(string[] codPapel, object userState) {
            if ((this.ObterCotacoesOperationCompleted == null)) {
                this.ObterCotacoesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterCotacoesOperationCompleted);
            }
            this.InvokeAsync("ObterCotacoes", new object[] {
                        codPapel}, this.ObterCotacoesOperationCompleted, userState);
        }
        
        private void OnObterCotacoesOperationCompleted(object arg) {
            if ((this.ObterCotacoesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterCotacoesCompleted(this, new ObterCotacoesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cotacao.sjdr.com.br/ObterCotacao", RequestNamespace="http://cotacao.sjdr.com.br/", ResponseNamespace="http://cotacao.sjdr.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DadosCotacao ObterCotacao(string codPapel) {
            object[] results = this.Invoke("ObterCotacao", new object[] {
                        codPapel});
            return ((DadosCotacao)(results[0]));
        }
        
        /// <remarks/>
        public void ObterCotacaoAsync(string codPapel) {
            this.ObterCotacaoAsync(codPapel, null);
        }
        
        /// <remarks/>
        public void ObterCotacaoAsync(string codPapel, object userState) {
            if ((this.ObterCotacaoOperationCompleted == null)) {
                this.ObterCotacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterCotacaoOperationCompleted);
            }
            this.InvokeAsync("ObterCotacao", new object[] {
                        codPapel}, this.ObterCotacaoOperationCompleted, userState);
        }
        
        private void OnObterCotacaoOperationCompleted(object arg) {
            if ((this.ObterCotacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterCotacaoCompleted(this, new ObterCotacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cotacao.sjdr.com.br/")]
    public partial class DadosCotacao {
        
        private string codAtivoField;
        
        private string descAtivoField;
        
        private string datPregaoField;
        
        private string horCotacaoField;
        
        private decimal valAberturaField;
        
        private decimal valMaximoField;
        
        private decimal valMinimoField;
        
        private decimal valMedioField;
        
        private decimal qtdVariacaoField;
        
        private string qtdVolumeField;
        
        private decimal valAtualField;
        
        private decimal[] valOfertaCompraField;
        
        private decimal[] valOfertaVendaField;
        
        private string numNegociosField;
        
        private decimal valFechamentoField;
        
        /// <remarks/>
        public string codAtivo {
            get {
                return this.codAtivoField;
            }
            set {
                this.codAtivoField = value;
            }
        }
        
        /// <remarks/>
        public string descAtivo {
            get {
                return this.descAtivoField;
            }
            set {
                this.descAtivoField = value;
            }
        }
        
        /// <remarks/>
        public string datPregao {
            get {
                return this.datPregaoField;
            }
            set {
                this.datPregaoField = value;
            }
        }
        
        /// <remarks/>
        public string horCotacao {
            get {
                return this.horCotacaoField;
            }
            set {
                this.horCotacaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valAbertura {
            get {
                return this.valAberturaField;
            }
            set {
                this.valAberturaField = value;
            }
        }
        
        /// <remarks/>
        public decimal valMaximo {
            get {
                return this.valMaximoField;
            }
            set {
                this.valMaximoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valMinimo {
            get {
                return this.valMinimoField;
            }
            set {
                this.valMinimoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valMedio {
            get {
                return this.valMedioField;
            }
            set {
                this.valMedioField = value;
            }
        }
        
        /// <remarks/>
        public decimal qtdVariacao {
            get {
                return this.qtdVariacaoField;
            }
            set {
                this.qtdVariacaoField = value;
            }
        }
        
        /// <remarks/>
        public string qtdVolume {
            get {
                return this.qtdVolumeField;
            }
            set {
                this.qtdVolumeField = value;
            }
        }
        
        /// <remarks/>
        public decimal valAtual {
            get {
                return this.valAtualField;
            }
            set {
                this.valAtualField = value;
            }
        }
        
        /// <remarks/>
        public decimal[] valOfertaCompra {
            get {
                return this.valOfertaCompraField;
            }
            set {
                this.valOfertaCompraField = value;
            }
        }
        
        /// <remarks/>
        public decimal[] valOfertaVenda {
            get {
                return this.valOfertaVendaField;
            }
            set {
                this.valOfertaVendaField = value;
            }
        }
        
        /// <remarks/>
        public string numNegocios {
            get {
                return this.numNegociosField;
            }
            set {
                this.numNegociosField = value;
            }
        }
        
        /// <remarks/>
        public decimal valFechamento {
            get {
                return this.valFechamentoField;
            }
            set {
                this.valFechamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ObterCotacoesCompletedEventHandler(object sender, ObterCotacoesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterCotacoesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterCotacoesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DadosCotacao[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DadosCotacao[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ObterCotacaoCompletedEventHandler(object sender, ObterCotacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterCotacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterCotacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DadosCotacao Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DadosCotacao)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591